framework:
  validation: PERMISSIVE

routes:
  OrderProcessor:
    #from: jms:queue:orders?connectionFactory=#jmsConnectionFactory
    from: direct:orders
    bindings:
      ToInventory:  direct:inventory
      ToPayment:    direct:payment
      ToFraudCheck: direct:fraudCheck
      
    errorHandler:
      deadLetter: jms:queue:deadLetter?connectionFactory=#jmsConnectionFactory
      maxRetries: 3
  FraudCheckProcessor:
    from: direct:fraudCheck
    bindings:
      ToManagement:  jms:queue:fraudManagement?connectionFactory=#jmsConnectionFactory
      ToArchive: jms:queue:fraudArchive?connectionFactory=#jmsConnectionFactory
      ToCollector: jms:queue:fraudCollector?connectionFactory=#jmsConnectionFactory
      
    errorHandler:
      deadLetter: jms:queue:deadLetter?connectionFactory=#jmsConnectionFactory
      maxRetries: 3
  PaymentProcessor:
    from: direct:payment
    bindings:
      ToRegister:  jms:queue:register?connectionFactory=#jmsConnectionFactory
      ToWireTransfer: jms:queue:wireTransfer?connectionFactory=#jmsConnectionFactory
      ToCredit: jms:queue:credit?connectionFactory=#jmsConnectionFactory
      
    errorHandler:
      deadLetter: jms:queue:deadLetter?connectionFactory=#jmsConnectionFactory
      maxRetries: 3
  InventoryProcessor:
    from: direct:inventory
    bindings:
      ToBookkeeping:  jms:queue:bookkeeping?connectionFactory=#jmsConnectionFactory
      ToInventoryFraudCheck: jms:queue:inventoryFraudCheck?connectionFactory=#jmsConnectionFactory
      ToWarehouse: jms:queue:warehouse?connectionFactory=#jmsConnectionFactory
      
    errorHandler:
      deadLetter: jms:queue:deadLetter?connectionFactory=#jmsConnectionFactory
      maxRetries: 3
