framework:
  validation: STRICT

routes:
#  CoprocessorIngressProcessor:
#    from: seda:raw-uart-ingress?discardWhenFull=true
#    bindings:
#      TelemetrySampled: seda:analog-pipeline
#      StateUpdated: seda:digital-pipeline
#      HardwareFault: log:malformed-hardware-frame?level=WARN

  DigitalStateProcessor:
    from: seda:digital-ingress?discardWhenFull=true
    bindings:
      StatePublished: log:digital-bridge?level=INFO
      HardwareFault: log:malformed-hardware-frame?level=WARN
      IgnoreSample: log:com.example.route?level=OFF
        

  AnalogTelemetryProcessor:
    from: seda:analog-ingress?discardWhenFull=true
    sample:
      samplePeriodMillis: 10000
    bindings:
        StatePublished: log:analog-bridge?level=INFO
        HardwareFault: log:malformed-hardware-frame?level=WARN
        IgnoreSample: log:com.example.route?level=OFF