framework:
  validation: STRICT

routes:
#  CoprocessorIngressProcessor:
#    from: seda:raw-uart-ingress?discardWhenFull=true
#    bindings:
#      TelemetrySampled: seda:analog-pipeline
#      StateUpdated: seda:digital-pipeline
#      HardwareFault: log:malformed-hardware-frame?level=WARN

  DigitalStatePipeline:
    from: seda:digital-ingress?discardWhenFull=true
    bindings:
      ChangedState:
        - uri: log:com.example.route?level=OFF

  AnalogTelemetryPipeline:
    from: seda:analog-ingress?discardWhenFull=true
    sample:
      samplePeriodMillis: 10000
    bindings:
        IgnoreSample:
          - uri: log:com.example.route?level=OFF