framework:
  validation: STRICT

routes:

  AnalogTelemetryPipeline:
    from: direct:coprocessor-events
    bindings:
        IgnoreSample:
          - uri: log:com.example.route?level=OFF
            throttler:
              requestsPerPeriod: 2
              timePeriodMillis: 1000
              enabled: true
        